---
- hosts: 172.31.12.242
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install java
    apt:
     name: apache2
     state: present
  - name: i want to create a folder
    file:
     path: /home/maha/myfolder
     state: directory

  - name: copy a file into node side
    copy:
     src: mytextfile
     dest: /home/maha/myfolder/mytextfile
  