---
- hosts: mywebserers
  become: yes
  tasks:
  - name: install java on debian
    apt:
     name: "{{myubuntujavapack}}"
     state: present

  - name: install java on redhat
    dnf:
     name: "{{myredhatjavapack}}"
     state: present