---
- hosts: mywebserers
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install apache2 webserver ( apt-get install apache2 webserver )
    apt:
     name: "{{myubuntuwebpack}}"
     state: present
    when: ansible_os_family=="debian"

  - name: i want to start my webserver ( service apache2 start )
    service:
     name: "{{myubuntuwebpack}}"
     state: started
    when: ansible_os_family=="debian"


  - name: i want to install httpd webserver ( yum install httpd )
    dnf:
     name: "{{myredhatwebpack}}"
     state: present
    when: ansible_os_family=="redhat"


  - name: i want to start httpd server ( service httpd start )
    service:
     name: "{{myredhatwebpack}}"
     state: started
    when: ansible_os_family=="redhat"