---
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2 webserver ( apt-get install apache2 webserver )
    apt:
     name: apache2
     state: present

  - name: i want to start my webserver ( service apache2 start )
    service:
     name: apache2
     state: started